# Generated by Django 5.2.4 on 2025-07-25 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message="Reyting 1 dan kam bo'lishi mumkin emas."), django.core.validators.MaxValueValidator(5, message="Reyting 5 dan ko'p bo'lishi mumkin emas.")], verbose_name='Reyting (1-5)'),
        ),
    ]
