# Generated by Django 5.2.4 on 2025-07-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_product_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, null=True, verbose_name='Texnik xususiyatlari'),
        ),
    ]
